### ISSUE TITLE
Compatibility with Community Edition images

### ISSUE THREAD

**Issue by robd003** [aerospike/aerospike-kubernetes-operator#106]
Just wondering if I could change the image from aerospike-server-enterprise to aerospike and use the community edition.

Is there anything about the operator that **requires** the enterprise edition of aerospike?

**Comment by rbotzer** [comment]
@robd003 the intention of this project is to provide a Kubernetes Operator for Aerospike Enterprise Edition. It leverages enterprise features such as quiescing a node, and is intended to work with non-CE images.  It also deals with ACLs, TLS setup, encryption-at-rest and other enterprise features. See our developer blog post [Developing a Kubernetes Operator for a Real Time Data Platform](https://medium.com/aerospike-developer-blog/developing-a-kubernetes-operator-for-a-real-time-data-platform-5819e1a10d26).

There is an older Kubernetes Operator for Aerospike Community Edition from Travel Audience (see [aerospike-operator: Aerospike atop Kubernetes made easy](https://tech.travelaudience.com/aerospike-operator-aerospike-atop-kubernetes-made-easy-e79301dd8c35)), which we promote on our [Launchpad](https://aerospike.com/community/launchpad/).

If you're interested in a CE Operator, I suggest getting involved with the community project [travelaudience/aerospike-operator](https://github.com/travelaudience/aerospike-operator). Otherwise, this EE Operator project [aerospike-kubernetes-operator](https://github.com/aerospike/aerospike-kubernetes-operator) is the one that engineers from Aerospike and multiple enterprise customers are working on together.
