### ISSUE TITLE
Operator start scaling the next rack while there are still migrations active due to scale of previous rack

### ISSUE THREAD

**Issue by Tema** [aerospike/aerospike-kubernetes-operator#109]
When we change CR to bump a number of replicas, we expect that operator will scale out StatefulSets by one rack at a time and wait until the migrations are completed before going to the next rack. However, we observed that if migrations take a long time then the operator starts scaling StatefulSet belonging to the next rack before cluster get stable with migrations.

**Comment by ashishshinde** [comment]
@Tema Scaling up while migrating is safety and not a performance issue. As far as safety is concerned, during migration when we are scaling up there is not loss of data unless more than replication factor nodes crash (same as non-migration case).

Waiting for migrations for every scaled up node will prolong scale up operation and also increase the overall number of migrations.

This is the reason operator scales in bulk instead of one node at a time.

**Comment by arrowplum** [comment]
What is going on, as far as I understand, is that while the operator does not wait for migrations _it_does_ wait for a rack to be up before moving on to the next rack.
